### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by mobileoverlord** [hexpm/pbcs#2]
The name `hex_crypto` implies that this dependency has to do with `hex` directly, when in fact its that it was split off from `hex`. In preparation for releasing this on `hex` I would like to change its name to something more generic. The only idea I have come up with so far is `pbcs` for `Password-Based Cryptography Specification` from https://tools.ietf.org/html/rfc8018

@potatosalad Does this name apply / make sense?

**Comment by potatosalad** [comment]
I'd say either `pbcs` or `pkcs5`, maybe?

I can't find many examples out there of people using `pbcs` (outside of some Oracle documentation), but there are a whole lot of uses of `pkcs5`.

Possible Reasons:

The PKCS standards have numbers assigned to the kinds of operations you perform: https://en.wikipedia.org/wiki/PKCS

The naming of the `PKCS#5` operations document has changed a few times in the past:
* [PKCS#5: Version 1.0](https://stuff.mit.edu/afs/sipb/user/warlord/afscell/OldFiles/RSA/overview.ps.Z
) &mdash; Password-Based Encryption Standard
* [PKCS#5: Version 1.5](https://pdfs.semanticscholar.org/ed73/514073880d314fd059c62c51fb8168ea7092.pdf) &mdash; Password-Based Encryption Standard
* [PKCS#5: Version 2.0](https://tools.ietf.org/html/rfc2898) &mdash; Password-Based Cryptography Specification
* [PKCS#5: Version 2.1](https://tools.ietf.org/html/rfc8018) &mdash; Password-Based Cryptography Specification

**Comment by mobileoverlord** [comment]
If there is more visibility for `pkcs5` I’d say we go with that. Besides, I think `hex_names_are_hard` is overloaded.

**Comment by ericmj** [comment]
Renamed project also

**Comment by mobileoverlord** [comment]
Fixed and published as `pbcs`
