### ISSUE TITLE
RFC 8018 / PKCS #5 Version 2.1

### ISSUE THREAD

**Issue by fhunleth** [hexpm/pbcs#9]
I'd send a PR, but I feel pretty ignorant on this topic. Should the RFC reference in the README.md be to RFC 8018 instead of RFC 2898? RFC 2898 is marked obsolete - I assume in Jan 2017 when 8018 was published. 

Looking at the change notes for RFC 8018 makes me think that this implementation would be compatible with it as well.

**Comment by mobileoverlord** [comment]
@potatosalad might know the answer to this but it seems safe

**Comment by fhunleth** [comment]
@potatosalad Thanks for the in-depth reply. I tried to turn part of it into a PR for the next person who comes across this library.
